version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "boo"
      MONGO_INITDB_ROOT_PASSWORD: "boo"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "boo"
      ME_CONFIG_BASICAUTH_PASSWORD: "boo"
      ME_CONFIG_MONGODB_URL: "mongodb://boo:boo@mongo:27017/"